source 'https://rubygems.org'

ruby '2.3.3'

gem 'rails', '~> 5.0.2'
gem 'pg', '~> 0.20'
gem 'puma', '~> 3.9'
gem 'rake', '~> 12.0'

gem 'active_model_serializers', '~> 0.10'
gem 'active_record-acts_as', '~> 2.4'
gem 'apipie-rails', '~> 0.5'
gem 'bcrypt', '~> 3.1.11'
gem 'bunny', '~> 2.6'
gem 'cancancan', '~> 1.17'
gem 'carrierwave', '~> 1.1'
gem 'carrierwave-base64', '~> 2.5'
gem 'dotenv-rails', '~> 2.2'
gem 'faker', '~> 1.7'
gem 'has_scope', '~> 0.7'
gem 'jwt', '~> 1.5'
gem 'listen', '~> 3.0.5'
gem 'mini_magick', '~> 4.7'
gem 'oj', '~> 2.18'
gem 'oj_mimic_json', '~> 1.0'
gem 'rails-i18n', '~> 5.0.0'
gem 'rails_admin', '1.1.0'
gem 'rails_admin-i18n', '~> 1.11'
gem 'sneakers', '~> 2.5'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'factory_girl_rails', '~> 4.8'
end

group :development do
  gem 'capistrano',           '~> 3.8', require: false
  gem 'capistrano-bundler',   '~> 1.2', require: false
  gem 'capistrano-rails',     '~> 1.2', require: false
  gem 'capistrano-rvm',       '~> 0.1', require: false
  # gem 'capistrano-sneakers',  require: false,
  #                             git: 'https://github.com/inventionlabsSydney/capistrano-sneakers.git',
  #                             ref: '63514ab504341e92f73380a210b405997ff073f7'
  gem 'capistrano3-puma',     '~> 3.1', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
